/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    ContactModal: typeof import('./src/components/ContactModal.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    LogoBox: typeof import('./src/components/LogoBox.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
